version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sunnyday_db
    env_file:
      - .env-non-dev
    # volumes:
    #   - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432


  redis:
    image: redis:7
    container_name: sunnyday_redis
    ports:
      - 6379:6379

  sunnyday:
    build: 
      context: .
    container_name:  sunnyday_app
    env_file:
      - .env-non-dev
    depends_on:
      - db 
      - redis
    command: ["/sunnyday/docker_scripts/app.sh"]
    ports:
      - 8000:8000

  celery:    
    build: 
      context: .
    container_name: sunnyday_celery
    env_file:
      - .env-non-dev
    command: ["/sunnyday/docker_scripts/celery.sh","celery"]
    depends_on:
      - sunnyday
    
  flower:    
    build: 
      context: .
    container_name: sunnyday_flower
    env_file:
      - .env-non-dev
    command: ["/sunnyday/docker_scripts/celery.sh","flower"]
    depends_on:
      - celery

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - sunnyday

# volumes:
#   postgresql_data:
